-- MySQL Script generated by MySQL Workbench
-- Tue Jun 22 09:37:28 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`VrstaUporabnika`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VrstaUporabnika` (
  `idVrstaUporabnika` INT NOT NULL,
  `ImeVrste` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idVrstaUporabnika`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Uporabnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Uporabnik` (
  `idUporabnik` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `Ime` VARCHAR(45) NOT NULL,
  `naslov` VARCHAR(45) NOT NULL,
  `TelSte` VARCHAR(45) NOT NULL,
  `Spol` VARCHAR(8) NOT NULL,
  `DatumRojstva` VARCHAR(45) NOT NULL,
  `idVrstaUporabnika` INT NOT NULL,
  PRIMARY KEY (`idUporabnik`),
  INDEX `fk_Uporabnik_VrstaUporabnika_idx` (`idVrstaUporabnika` ASC) VISIBLE,
  CONSTRAINT `fk_Uporabnik_VrstaUporabnika`
    FOREIGN KEY (`idVrstaUporabnika`)
    REFERENCES `mydb`.`VrstaUporabnika` (`idVrstaUporabnika`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vrstaProdukta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vrstaProdukta` (
  `idvrstaProdukta` INT NOT NULL,
  `Imevrste` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idvrstaProdukta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produkt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produkt` (
  `idProdukt` INT NOT NULL,
  `ImeProdukta` VARCHAR(45) NOT NULL,
  `Opis` VARCHAR(45) NOT NULL,
  `Cena` DECIMAL(5) NOT NULL,
  `imgsource` VARCHAR(45) NOT NULL,
  `idvrstaProdukta` INT NOT NULL,
  `zaloga` INT NOT NULL,
  PRIMARY KEY (`idProdukt`, `idvrstaProdukta`),
  INDEX `fk_Produkt_vrstaProdukta1_idx` (`idvrstaProdukta` ASC) VISIBLE,
  CONSTRAINT `fk_Produkt_vrstaProdukta1`
    FOREIGN KEY (`idvrstaProdukta`)
    REFERENCES `mydb`.`vrstaProdukta` (`idvrstaProdukta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`narocilo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`narocilo` (
  `idnarocilo` INT NOT NULL,
  `Celotnacena` FLOAT NOT NULL,
  `idUporabnik` INT NOT NULL,
  PRIMARY KEY (`idnarocilo`),
  INDEX `fk_narocilo_Uporabnik1_idx` (`idUporabnik` ASC) VISIBLE,
  CONSTRAINT `fk_narocilo_Uporabnik1`
    FOREIGN KEY (`idUporabnik`)
    REFERENCES `mydb`.`Uporabnik` (`idUporabnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`narocilo_izdelek`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`narocilo_izdelek` (
  `idnarocilo_izdelek` INT NULL,
  `stevilo` INT NOT NULL,
  `narocilo_idnarocilo` INT NOT NULL,
  `Produkt_idProdukt` INT NOT NULL,
  `Produkt_idvrstaProdukta` INT NOT NULL,
  PRIMARY KEY (`idnarocilo_izdelek`),
  INDEX `fk_narocilo_izdelek_narocilo1_idx` (`narocilo_idnarocilo` ASC) VISIBLE,
  INDEX `fk_narocilo_izdelek_Produkt1_idx` (`Produkt_idProdukt` ASC, `Produkt_idvrstaProdukta` ASC) VISIBLE,
  CONSTRAINT `fk_narocilo_izdelek_narocilo1`
    FOREIGN KEY (`narocilo_idnarocilo`)
    REFERENCES `mydb`.`narocilo` (`idnarocilo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_narocilo_izdelek_Produkt1`
    FOREIGN KEY (`Produkt_idProdukt` , `Produkt_idvrstaProdukta`)
    REFERENCES `mydb`.`Produkt` (`idProdukt` , `idvrstaProdukta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`kosarica_izdelek`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`kosarica_izdelek` (
  `idkosarica_izdelek` INT NOT NULL,
  `kosarica_idkosarica` INT NOT NULL,
  `stevilo` INT NOT NULL,
  `aktivno` INT NOT NULL,
  `Produkt_idProdukt` INT NOT NULL,
  `Produkt_idvrstaProdukta` INT NOT NULL,
  `Uporabnik_idUporabnik` INT NOT NULL,
  PRIMARY KEY (`idkosarica_izdelek`),
  INDEX `fk_kosarica_izdelek_Produkt1_idx` (`Produkt_idProdukt` ASC, `Produkt_idvrstaProdukta` ASC) VISIBLE,
  INDEX `fk_kosarica_izdelek_Uporabnik1_idx` (`Uporabnik_idUporabnik` ASC) VISIBLE,
  CONSTRAINT `fk_kosarica_izdelek_Produkt1`
    FOREIGN KEY (`Produkt_idProdukt` , `Produkt_idvrstaProdukta`)
    REFERENCES `mydb`.`Produkt` (`idProdukt` , `idvrstaProdukta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_kosarica_izdelek_Uporabnik1`
    FOREIGN KEY (`Uporabnik_idUporabnik`)
    REFERENCES `mydb`.`Uporabnik` (`idUporabnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
